{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rca-operator.fullname" . }}-metrics
  namespace: {{ include "rca-operator.namespace" . }}
  labels:
    {{- include "rca-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "rca-operator.selectorLabels" . | nindent 4 }}
{{- end }}
