---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rca.rca-operator.io
  resources:
  - incidentreports
  - rcaagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rca.rca-operator.io
  resources:
  - incidentreports/finalizers
  - rcaagents/finalizers
  verbs:
  - update
- apiGroups:
  - rca.rca-operator.io
  resources:
  - incidentreports/status
  - rcaagents/status
  verbs:
  - get
  - patch
  - update
