apiVersion: rca.rca-operator.tech/v1alpha1
kind: IncidentReport
metadata:
  labels:
    app.kubernetes.io/name: rca-operator
    app.kubernetes.io/managed-by: kustomize
    rca.rca-operator.tech/severity: P2
    rca.rca-operator.tech/incident-type: OOM
  name: incidentreport-sample
  namespace: development
spec:
  agentRef: rcaagent-sample
