package autodetect

import (
	"context"
	"testing"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/log/zap"

	rcav1alpha1 "github.com/gaurangkudale/rca-operator/api/v1alpha1"
)

func newScheme() *runtime.Scheme {
	s := runtime.NewScheme()
	_ = rcav1alpha1.AddToScheme(s)
	return s
}

func newFakeClient(objs ...client.Object) client.Client {
	return fake.NewClientBuilder().
		WithScheme(newScheme()).
		WithObjects(objs...).
		Build()
}

func testCreator(c client.Client) *Creator {
	cfg := DefaultConfig()
	cfg.MaxAutoRules = 5
	creator := NewCreator(c, cfg, zap.New(zap.UseDevMode(true)))
	creator.nowFn = func() time.Time { return time.Date(2026, 4, 3, 12, 0, 0, 0, time.UTC) }
	return creator
}

func TestCreator_EnsureRule_Creates(t *testing.T) {
	fc := newFakeClient()
	cr := testCreator(fc)

	rec := &PatternRecord{
		Pair:        EventPair{TriggerType: "CrashLoopBackOff", ConditionType: "OOMKilled", Scope: "samePod"},
		FirstSeen:   time.Date(2026, 4, 3, 11, 0, 0, 0, time.UTC),
		LastSeen:    time.Date(2026, 4, 3, 11, 50, 0, 0, time.UTC),
		Occurrences: 7,
	}

	if err := cr.EnsureRule(context.Background(), rec); err != nil {
		t.Fatalf("EnsureRule failed: %v", err)
	}

	// Verify rule was created.
	rule := &rcav1alpha1.RCACorrelationRule{}
	if err := fc.Get(context.Background(), client.ObjectKey{Name: "auto-crashloopbackoff-oomkilled-samepod"}, rule); err != nil {
		t.Fatalf("rule not found: %v", err)
	}

	if rule.Labels[LabelAutoGenerated] != "true" {
		t.Error("expected auto-generated label")
	}
	if rule.Spec.Trigger.EventType != "CrashLoopBackOff" {
		t.Errorf("expected trigger CrashLoopBackOff, got %s", rule.Spec.Trigger.EventType)
	}
	if len(rule.Spec.Conditions) != 1 {
		t.Fatalf("expected 1 condition, got %d", len(rule.Spec.Conditions))
	}
	if rule.Spec.Conditions[0].EventType != "OOMKilled" {
		t.Errorf("expected condition OOMKilled, got %s", rule.Spec.Conditions[0].EventType)
	}
	// CrashLoopBackOff=P3, OOMKilled=P2 → higher is P2.
	if rule.Spec.Fires.Severity != "P2" {
		t.Errorf("expected severity P2, got %s", rule.Spec.Fires.Severity)
	}
	if rec.RuleName != "auto-crashloopbackoff-oomkilled-samepod" {
		t.Errorf("expected RuleName set on record, got %q", rec.RuleName)
	}
}

func TestCreator_EnsureRule_UpdatesExisting(t *testing.T) {
	existing := &rcav1alpha1.RCACorrelationRule{
		ObjectMeta: metav1.ObjectMeta{
			Name: "auto-crashloopbackoff-oomkilled-samepod",
			Labels: map[string]string{
				LabelAutoGenerated: "true",
			},
			Annotations: map[string]string{
				AnnotationPatternKey:  "CrashLoopBackOff:OOMKilled:samePod",
				AnnotationOccurrences: "5",
				AnnotationLastSeen:    "2026-04-03T11:00:00Z",
			},
		},
		Spec: rcav1alpha1.RCACorrelationRuleSpec{
			Priority: 30,
			Trigger:  rcav1alpha1.RuleTrigger{EventType: "CrashLoopBackOff"},
			Conditions: []rcav1alpha1.RuleCondition{
				{EventType: "OOMKilled", Scope: "samePod"},
			},
			Fires: rcav1alpha1.RuleFires{
				IncidentType: "CrashLoopBackOff-OOMKilled",
				Severity:     "P2",
				Summary:      "test",
			},
		},
	}

	fc := newFakeClient(existing)
	cr := testCreator(fc)

	rec := &PatternRecord{
		Pair:        EventPair{TriggerType: "CrashLoopBackOff", ConditionType: "OOMKilled", Scope: "samePod"},
		Occurrences: 10,
	}

	if err := cr.EnsureRule(context.Background(), rec); err != nil {
		t.Fatalf("EnsureRule update failed: %v", err)
	}

	// Verify annotations were updated.
	rule := &rcav1alpha1.RCACorrelationRule{}
	_ = fc.Get(context.Background(), client.ObjectKey{Name: "auto-crashloopbackoff-oomkilled-samepod"}, rule)

	if rule.Annotations[AnnotationOccurrences] != "10" {
		t.Errorf("expected occurrences=10, got %s", rule.Annotations[AnnotationOccurrences])
	}
	if rule.Annotations[AnnotationLastSeen] != "2026-04-03T12:00:00Z" {
		t.Errorf("expected updated last-seen, got %s", rule.Annotations[AnnotationLastSeen])
	}
}

func TestCreator_EnsureRule_RespectsMaxCap(t *testing.T) {
	// Pre-create 5 rules (at max).
	objs := make([]client.Object, 0, 5)
	for i := range 5 {
		objs = append(objs, &rcav1alpha1.RCACorrelationRule{
			ObjectMeta: metav1.ObjectMeta{
				Name:   RuleName(EventPair{TriggerType: "A", ConditionType: "B" + string(rune('0'+i)), Scope: "samePod"}),
				Labels: map[string]string{LabelAutoGenerated: "true"},
				Annotations: map[string]string{
					AnnotationPatternKey: "A:B" + string(rune('0'+i)) + ":samePod",
				},
			},
			Spec: rcav1alpha1.RCACorrelationRuleSpec{
				Priority: 20,
				Trigger:  rcav1alpha1.RuleTrigger{EventType: "A"},
				Fires:    rcav1alpha1.RuleFires{IncidentType: "X", Severity: "P3", Summary: "test"},
			},
		})
	}

	fc := newFakeClient(objs...)
	cr := testCreator(fc) // MaxAutoRules=5

	rec := &PatternRecord{
		Pair:        EventPair{TriggerType: "New", ConditionType: "Pattern", Scope: "samePod"},
		Occurrences: 10,
	}

	// Should not error, but should skip creation.
	if err := cr.EnsureRule(context.Background(), rec); err != nil {
		t.Fatalf("EnsureRule failed: %v", err)
	}

	// Verify new rule was NOT created.
	rule := &rcav1alpha1.RCACorrelationRule{}
	err := fc.Get(context.Background(), client.ObjectKey{Name: "auto-new-pattern-samepod"}, rule)
	if err == nil {
		t.Error("expected new rule not created (cap reached), but it was")
	}
}

func TestCreator_EnsureRule_SkipsUserRuleConflict(t *testing.T) {
	userRule := &rcav1alpha1.RCACorrelationRule{
		ObjectMeta: metav1.ObjectMeta{
			Name: "crashloop-plus-oom",
			// No auto-generated label → user rule.
		},
		Spec: rcav1alpha1.RCACorrelationRuleSpec{
			Priority: 400,
			Trigger:  rcav1alpha1.RuleTrigger{EventType: "CrashLoopBackOff"},
			Conditions: []rcav1alpha1.RuleCondition{
				{EventType: "OOMKilled", Scope: "samePod"},
			},
			Fires: rcav1alpha1.RuleFires{IncidentType: "OOMKilled", Severity: "P2", Summary: "user rule"},
		},
	}

	fc := newFakeClient(userRule)
	cr := testCreator(fc)

	rec := &PatternRecord{
		Pair:        EventPair{TriggerType: "CrashLoopBackOff", ConditionType: "OOMKilled", Scope: "samePod"},
		Occurrences: 10,
	}

	if err := cr.EnsureRule(context.Background(), rec); err != nil {
		t.Fatalf("EnsureRule failed: %v", err)
	}

	// Auto rule should NOT be created.
	rule := &rcav1alpha1.RCACorrelationRule{}
	err := fc.Get(context.Background(), client.ObjectKey{Name: "auto-crashloopbackoff-oomkilled-samepod"}, rule)
	if err == nil {
		t.Error("expected auto-rule not created (user rule conflict), but it was")
	}
}

func TestCreator_ExpireStaleRules(t *testing.T) {
	now := time.Date(2026, 4, 3, 12, 0, 0, 0, time.UTC)
	staleLastSeen := now.Add(-2 * time.Hour).Format(time.RFC3339)
	freshLastSeen := now.Add(-30 * time.Minute).Format(time.RFC3339)

	staleRule := &rcav1alpha1.RCACorrelationRule{
		ObjectMeta: metav1.ObjectMeta{
			Name:   "auto-stale-rule-samepod",
			Labels: map[string]string{LabelAutoGenerated: "true"},
			Annotations: map[string]string{
				AnnotationPatternKey: "Stale:Rule:samePod",
				AnnotationLastSeen:   staleLastSeen,
			},
		},
		Spec: rcav1alpha1.RCACorrelationRuleSpec{
			Priority: 20,
			Trigger:  rcav1alpha1.RuleTrigger{EventType: "Stale"},
			Fires:    rcav1alpha1.RuleFires{IncidentType: "X", Severity: "P3", Summary: "t"},
		},
	}
	freshRule := &rcav1alpha1.RCACorrelationRule{
		ObjectMeta: metav1.ObjectMeta{
			Name:   "auto-fresh-rule-samepod",
			Labels: map[string]string{LabelAutoGenerated: "true"},
			Annotations: map[string]string{
				AnnotationPatternKey: "Fresh:Rule:samePod",
				AnnotationLastSeen:   freshLastSeen,
			},
		},
		Spec: rcav1alpha1.RCACorrelationRuleSpec{
			Priority: 20,
			Trigger:  rcav1alpha1.RuleTrigger{EventType: "Fresh"},
			Fires:    rcav1alpha1.RuleFires{IncidentType: "X", Severity: "P3", Summary: "t"},
		},
	}

	fc := newFakeClient(staleRule, freshRule)
	cr := testCreator(fc)
	cr.nowFn = func() time.Time { return now }

	if err := cr.ExpireStaleRules(context.Background(), nil); err != nil {
		t.Fatalf("ExpireStaleRules failed: %v", err)
	}

	// Stale rule should be deleted.
	err := fc.Get(context.Background(), client.ObjectKey{Name: "auto-stale-rule-samepod"}, &rcav1alpha1.RCACorrelationRule{})
	if err == nil {
		t.Error("expected stale rule to be deleted")
	}

	// Fresh rule should still exist.
	err = fc.Get(context.Background(), client.ObjectKey{Name: "auto-fresh-rule-samepod"}, &rcav1alpha1.RCACorrelationRule{})
	if err != nil {
		t.Errorf("expected fresh rule to still exist: %v", err)
	}
}

func TestCreator_LoadExisting(t *testing.T) {
	rule := &rcav1alpha1.RCACorrelationRule{
		ObjectMeta: metav1.ObjectMeta{
			Name:   "auto-a-b-samepod",
			Labels: map[string]string{LabelAutoGenerated: "true"},
			Annotations: map[string]string{
				AnnotationPatternKey:  "A:B:samePod",
				AnnotationOccurrences: "10",
				AnnotationFirstSeen:   "2026-04-03T10:00:00Z",
				AnnotationLastSeen:    "2026-04-03T11:00:00Z",
			},
		},
		Spec: rcav1alpha1.RCACorrelationRuleSpec{
			Priority: 30,
			Trigger:  rcav1alpha1.RuleTrigger{EventType: "A"},
			Conditions: []rcav1alpha1.RuleCondition{
				{EventType: "B", Scope: "samePod"},
			},
			Fires: rcav1alpha1.RuleFires{IncidentType: "A-B", Severity: "P3", Summary: "test"},
		},
	}

	fc := newFakeClient(rule)
	cr := testCreator(fc)

	records, err := cr.LoadExisting(context.Background())
	if err != nil {
		t.Fatalf("LoadExisting failed: %v", err)
	}

	if len(records) != 1 {
		t.Fatalf("expected 1 record, got %d", len(records))
	}

	rec := records["A:B:samePod"]
	if rec == nil {
		t.Fatal("expected A:B:samePod record")
	}
	if rec.Occurrences != 10 {
		t.Errorf("expected 10 occurrences, got %d", rec.Occurrences)
	}
	if rec.RuleName != "auto-a-b-samepod" {
		t.Errorf("expected rule name auto-a-b-samepod, got %s", rec.RuleName)
	}
}

func TestHigherSeverity(t *testing.T) {
	tests := []struct {
		a, b, want string
	}{
		{"P1", "P2", "P1"},
		{"P3", "P2", "P2"},
		{"P4", "P4", "P4"},
		{"P3", "", "P3"},
		{"", "P2", "P2"},
	}
	for _, tt := range tests {
		got := higherSeverity(tt.a, tt.b)
		if got != tt.want {
			t.Errorf("higherSeverity(%q, %q) = %q, want %q", tt.a, tt.b, got, tt.want)
		}
	}
}
