package autodetect

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/go-logr/logr"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/labels"
	"sigs.k8s.io/controller-runtime/pkg/client"

	rcav1alpha1 "github.com/gaurangkudale/rca-operator/api/v1alpha1"
	"github.com/gaurangkudale/rca-operator/internal/signals"
)

const (
	// LabelAutoGenerated marks a rule as auto-generated by the detector.
	LabelAutoGenerated = "rca.rca-operator.tech/auto-generated"

	// AnnotationPatternKey stores the pattern dedup key on the rule.
	AnnotationPatternKey = "rca.rca-operator.tech/pattern-key"
	// AnnotationOccurrences stores the occurrence count.
	AnnotationOccurrences = "rca.rca-operator.tech/occurrences"
	// AnnotationFirstSeen stores when the pattern was first observed.
	AnnotationFirstSeen = "rca.rca-operator.tech/first-seen"
	// AnnotationLastSeen stores when the pattern was last observed.
	AnnotationLastSeen = "rca.rca-operator.tech/last-seen"

	// ValueTrue is the constant for label/annotation boolean "true" values.
	ValueTrue = "true"
)

// +kubebuilder:rbac:groups=rca.rca-operator.tech,resources=rcacorrelationrules,verbs=get;list;watch;create;update;delete

// Creator handles the Kubernetes lifecycle of auto-generated RCACorrelationRule CRDs.
type Creator struct {
	client client.Client
	log    logr.Logger
	config Config
	nowFn  func() time.Time

	// severityMap caches event type → default severity from signal mappings.
	severityMap map[string]string
}

// NewCreator returns a Creator ready to manage auto-generated rules.
func NewCreator(c client.Client, cfg Config, logger logr.Logger) *Creator {
	sevMap := make(map[string]string)
	for _, m := range signals.DefaultMappings() {
		sevMap[m.EventType] = m.Severity
	}
	return &Creator{
		client:      c,
		log:         logger.WithName("autodetect-creator"),
		config:      cfg,
		nowFn:       time.Now,
		severityMap: sevMap,
	}
}

// EnsureRule creates or updates an auto-generated RCACorrelationRule CRD for the
// given pattern. If the rule already exists, only annotations are updated.
func (c *Creator) EnsureRule(ctx context.Context, rec *PatternRecord) error {
	name := RuleName(rec.Pair)

	// Check cap.
	count, err := c.CountAutoRules(ctx)
	if err != nil {
		return fmt.Errorf("counting auto rules: %w", err)
	}
	if count >= c.config.MaxAutoRules && rec.RuleName == "" {
		c.log.Info("Auto-rule cap reached, skipping", "maxAutoRules", c.config.MaxAutoRules, "pattern", rec.Pair.Key())
		return nil
	}

	// Check for conflicting user-created rule.
	if c.userRuleExists(ctx, rec.Pair) {
		c.log.V(1).Info("User-created rule already covers this pattern", "pattern", rec.Pair.Key())
		return nil
	}

	// Try to find existing auto-generated rule.
	existing := &rcav1alpha1.RCACorrelationRule{}
	err = c.client.Get(ctx, client.ObjectKey{Name: name}, existing)
	if err == nil {
		// Update annotations only.
		return c.updateAnnotations(ctx, existing, rec)
	}

	// Create new rule.
	return c.createRule(ctx, name, rec)
}

// ExpireStaleRules deletes auto-generated rules whose pattern has not been
// observed within the configured expiry duration.
func (c *Creator) ExpireStaleRules(ctx context.Context, activePatterns map[string]*PatternRecord) error {
	rules, err := c.listAutoRules(ctx)
	if err != nil {
		return err
	}

	now := c.nowFn()
	for i := range rules {
		rule := &rules[i]
		lastSeenStr := rule.Annotations[AnnotationLastSeen]
		lastSeen, parseErr := time.Parse(time.RFC3339, lastSeenStr)
		if parseErr != nil {
			// Cannot parse — use creation time as fallback.
			lastSeen = rule.CreationTimestamp.Time
		}

		if now.Sub(lastSeen) > c.config.ExpiryDuration {
			patternKey := rule.Annotations[AnnotationPatternKey]
			c.log.Info("Expiring stale auto-generated rule",
				"rule", rule.Name,
				"patternKey", patternKey,
				"lastSeen", lastSeenStr,
				"expiryDuration", c.config.ExpiryDuration,
			)
			if err := c.client.Delete(ctx, rule); err != nil {
				c.log.Error(err, "Failed to delete expired auto-rule", "rule", rule.Name)
			}
		}
	}
	return nil
}

// CountAutoRules returns the number of auto-generated rules in the cluster.
func (c *Creator) CountAutoRules(ctx context.Context) (int, error) {
	rules, err := c.listAutoRules(ctx)
	if err != nil {
		return 0, err
	}
	return len(rules), nil
}

// LoadExisting returns all auto-generated rules from the cluster,
// keyed by their pattern-key annotation. Used at startup to seed the accumulator.
func (c *Creator) LoadExisting(ctx context.Context) (map[string]*PatternRecord, error) {
	rules, err := c.listAutoRules(ctx)
	if err != nil {
		return nil, err
	}

	records := make(map[string]*PatternRecord, len(rules))
	for _, rule := range rules {
		if rule.Annotations[AnnotationPatternKey] == "" {
			continue
		}

		occ, _ := strconv.Atoi(rule.Annotations[AnnotationOccurrences])
		firstSeen, _ := time.Parse(time.RFC3339, rule.Annotations[AnnotationFirstSeen])
		lastSeen, _ := time.Parse(time.RFC3339, rule.Annotations[AnnotationLastSeen])

		// Reconstruct EventPair from the rule spec and normalize to canonical
		// (lexicographic) order. This ensures old rules created before the
		// canonical-order fix are seeded under the correct key.
		pair := EventPair{
			TriggerType: rule.Spec.Trigger.EventType,
			Scope:       "samePod", // default
		}
		if len(rule.Spec.Conditions) > 0 {
			pair.ConditionType = rule.Spec.Conditions[0].EventType
			pair.Scope = rule.Spec.Conditions[0].Scope
		}
		pair = NormalizePair(pair)

		canonicalKey := pair.Key()
		// If a canonical record already exists (from the mirror rule), merge by
		// keeping the higher occurrence count and wider time window.
		if existing, ok := records[canonicalKey]; ok {
			if occ > existing.Occurrences {
				existing.Occurrences = occ
			}
			if firstSeen.Before(existing.FirstSeen) {
				existing.FirstSeen = firstSeen
			}
			if lastSeen.After(existing.LastSeen) {
				existing.LastSeen = lastSeen
			}
			continue
		}

		records[canonicalKey] = &PatternRecord{
			Pair:        pair,
			FirstSeen:   firstSeen,
			LastSeen:    lastSeen,
			Occurrences: occ,
			RuleName:    rule.Name,
		}
	}
	return records, nil
}

func (c *Creator) createRule(ctx context.Context, name string, rec *PatternRecord) error {
	severity := c.resolveSeverity(rec.Pair)
	priority := c.config.AutoRulePriority
	now := c.nowFn()

	rule := &rcav1alpha1.RCACorrelationRule{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
			Labels: map[string]string{
				LabelAutoGenerated: ValueTrue,
			},
			Annotations: map[string]string{
				AnnotationPatternKey:  rec.Pair.Key(),
				AnnotationOccurrences: strconv.Itoa(rec.Occurrences),
				AnnotationFirstSeen:   rec.FirstSeen.Format(time.RFC3339),
				AnnotationLastSeen:    now.Format(time.RFC3339),
			},
		},
		Spec: rcav1alpha1.RCACorrelationRuleSpec{
			Priority: priority,
			Trigger: rcav1alpha1.RuleTrigger{
				EventType: rec.Pair.TriggerType,
			},
			Conditions: []rcav1alpha1.RuleCondition{
				{
					EventType: rec.Pair.ConditionType,
					Scope:     rec.Pair.Scope,
				},
			},
			Fires: rcav1alpha1.RuleFires{
				IncidentType: rec.Pair.TriggerType + "-" + rec.Pair.ConditionType,
				Severity:     severity,
				Summary:      buildAutoSummary(rec.Pair),
			},
		},
	}

	if err := c.client.Create(ctx, rule); err != nil {
		return fmt.Errorf("creating auto-rule %s: %w", name, err)
	}

	rec.RuleName = name
	c.log.Info("Created auto-generated correlation rule",
		"rule", name,
		"trigger", rec.Pair.TriggerType,
		"condition", rec.Pair.ConditionType,
		"scope", rec.Pair.Scope,
		"occurrences", rec.Occurrences,
		"priority", priority,
	)
	return nil
}

func (c *Creator) updateAnnotations(ctx context.Context, rule *rcav1alpha1.RCACorrelationRule, rec *PatternRecord) error {
	if rule.Annotations == nil {
		rule.Annotations = make(map[string]string)
	}
	rule.Annotations[AnnotationOccurrences] = strconv.Itoa(rec.Occurrences)
	rule.Annotations[AnnotationLastSeen] = c.nowFn().Format(time.RFC3339)

	if err := c.client.Update(ctx, rule); err != nil {
		return fmt.Errorf("updating auto-rule %s: %w", rule.Name, err)
	}
	return nil
}

func (c *Creator) listAutoRules(ctx context.Context) ([]rcav1alpha1.RCACorrelationRule, error) {
	list := &rcav1alpha1.RCACorrelationRuleList{}
	sel, _ := labels.Parse(LabelAutoGenerated + "=true")
	if err := c.client.List(ctx, list, &client.ListOptions{LabelSelector: sel}); err != nil {
		return nil, fmt.Errorf("listing auto-generated rules: %w", err)
	}
	return list.Items, nil
}

func (c *Creator) userRuleExists(ctx context.Context, pair EventPair) bool {
	list := &rcav1alpha1.RCACorrelationRuleList{}
	if err := c.client.List(ctx, list); err != nil {
		return false
	}
	for _, rule := range list.Items {
		// Skip auto-generated rules.
		if rule.Labels[LabelAutoGenerated] == ValueTrue {
			continue
		}
		// Check if this user rule covers the same trigger + condition + scope.
		if rule.Spec.Trigger.EventType != pair.TriggerType {
			continue
		}
		for _, cond := range rule.Spec.Conditions {
			if cond.EventType == pair.ConditionType && cond.Scope == pair.Scope {
				return true
			}
		}
	}
	return false
}

// resolveSeverity picks the higher severity from the two event types' default mappings.
func (c *Creator) resolveSeverity(pair EventPair) string {
	s1 := c.severityMap[pair.TriggerType]
	s2 := c.severityMap[pair.ConditionType]
	return higherSeverity(s1, s2)
}

func higherSeverity(a, b string) string {
	rank := map[string]int{"P1": 4, "P2": 3, "P3": 2, "P4": 1}
	ra, rb := rank[a], rank[b]
	if ra >= rb {
		return a
	}
	return b
}

// buildAutoSummary generates a scope-appropriate summary template for an
// auto-detected correlation rule.
func buildAutoSummary(pair EventPair) string {
	switch pair.Scope {
	case "sameNode":
		return fmt.Sprintf(
			"%s correlated with %s on node {{.NodeName}}",
			pair.TriggerType, pair.ConditionType,
		)
	case "sameNamespace":
		return fmt.Sprintf(
			"%s correlated with %s in namespace {{.Namespace}}",
			pair.TriggerType, pair.ConditionType,
		)
	default: // samePod
		return fmt.Sprintf(
			"%s correlated with %s on pod {{.PodName}} in {{.Namespace}}",
			pair.TriggerType, pair.ConditionType,
		)
	}
}
