package autodetect

import (
	"context"
	"testing"
	"time"

	"sigs.k8s.io/controller-runtime/pkg/log/zap"

	rcav1alpha1 "github.com/gaurangkudale/rca-operator/api/v1alpha1"
	"github.com/gaurangkudale/rca-operator/internal/correlator"
	"github.com/gaurangkudale/rca-operator/internal/watcher"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func TestDetector_Tick_CreatesRule(t *testing.T) {
	buf := correlator.NewBuffer(5 * time.Minute)
	fc := newFakeClient()
	cfg := DefaultConfig()
	cfg.MinOccurrences = 3
	cfg.MinTimeSpan = 0 // disable for test
	cfg.ConfidenceThreshold = 0.5
	cfg.MaxAutoRules = 10

	det := NewDetector(buf, fc, cfg, zap.New(zap.UseDevMode(true)))
	det.seeded = true // skip startup seed

	now := time.Now()

	// Simulate 3 ticks with CrashLoopBackOff + OOMKilled on same pod.
	for range 3 {
		buf.Add(watcher.CrashLoopBackOffEvent{
			BaseEvent: watcher.BaseEvent{At: now, Namespace: "default", PodName: "pod-1", NodeName: "node-1"},
		})
		buf.Add(watcher.OOMKilledEvent{
			BaseEvent: watcher.BaseEvent{At: now.Add(time.Second), Namespace: "default", PodName: "pod-1", NodeName: "node-1"},
		})
		det.tick(context.Background())
	}

	// Verify rule was created.
	rule := &rcav1alpha1.RCACorrelationRule{}
	err := fc.Get(context.Background(), client.ObjectKey{Name: "auto-crashloopbackoff-oomkilled-samepod"}, rule)
	if err != nil {
		t.Fatalf("expected auto-rule to be created: %v", err)
	}

	if rule.Labels[LabelAutoGenerated] != "true" {
		t.Error("expected auto-generated label")
	}
	if rule.Spec.Trigger.EventType != "CrashLoopBackOff" {
		t.Errorf("expected trigger CrashLoopBackOff, got %s", rule.Spec.Trigger.EventType)
	}
	if rule.Spec.Fires.Severity != "P2" {
		t.Errorf("expected severity P2 (higher of P3+P2), got %s", rule.Spec.Fires.Severity)
	}
}

func TestDetector_Tick_NoRuleBeforeThreshold(t *testing.T) {
	buf := correlator.NewBuffer(5 * time.Minute)
	fc := newFakeClient()
	cfg := DefaultConfig()
	cfg.MinOccurrences = 5
	cfg.MinTimeSpan = 0
	cfg.ConfidenceThreshold = 0.5

	det := NewDetector(buf, fc, cfg, zap.New(zap.UseDevMode(true)))
	det.seeded = true

	// Only 2 ticks — below threshold.
	for range 2 {
		now := time.Now()
		buf.Add(watcher.CrashLoopBackOffEvent{
			BaseEvent: watcher.BaseEvent{At: now, Namespace: "default", PodName: "pod-1"},
		})
		buf.Add(watcher.OOMKilledEvent{
			BaseEvent: watcher.BaseEvent{At: now.Add(time.Second), Namespace: "default", PodName: "pod-1"},
		})
		det.tick(context.Background())
	}

	// Rule should NOT exist yet.
	list := &rcav1alpha1.RCACorrelationRuleList{}
	_ = fc.List(context.Background(), list)
	if len(list.Items) != 0 {
		t.Errorf("expected no rules before threshold, got %d", len(list.Items))
	}
}

func TestDetector_SeedsFromExisting(t *testing.T) {
	existingRule := &rcav1alpha1.RCACorrelationRule{}
	existingRule.Name = "auto-a-b-samepod"
	existingRule.Labels = map[string]string{LabelAutoGenerated: "true"}
	existingRule.Annotations = map[string]string{
		AnnotationPatternKey:  "A:B:samePod",
		AnnotationOccurrences: "10",
		AnnotationFirstSeen:   time.Now().Add(-time.Hour).Format(time.RFC3339),
		AnnotationLastSeen:    time.Now().Add(-5 * time.Minute).Format(time.RFC3339),
	}
	existingRule.Spec = rcav1alpha1.RCACorrelationRuleSpec{
		Priority: 30,
		Trigger:  rcav1alpha1.RuleTrigger{EventType: "A"},
		Conditions: []rcav1alpha1.RuleCondition{
			{EventType: "B", Scope: "samePod"},
		},
		Fires: rcav1alpha1.RuleFires{IncidentType: "A-B", Severity: "P3", Summary: "test"},
	}

	buf := correlator.NewBuffer(5 * time.Minute)
	fc := newFakeClient(existingRule)
	cfg := DefaultConfig()

	det := NewDetector(buf, fc, cfg, zap.New(zap.UseDevMode(true)))

	// Run seed.
	det.seedFromExisting(context.Background())

	// Accumulator should have the seeded pattern.
	if det.accumulator.Count() != 1 {
		t.Errorf("expected 1 seeded pattern, got %d", det.accumulator.Count())
	}

	all := det.accumulator.All()
	rec := all["A:B:samePod"]
	if rec == nil {
		t.Fatal("expected A:B:samePod in accumulator")
	}
	if rec.RuleName != "auto-a-b-samepod" {
		t.Errorf("expected RuleName=auto-a-b-samepod, got %s", rec.RuleName)
	}
}
