apiVersion: v2
name: rca-operator
description: An AI-powered SRE Operator that watches your cluster 24x7 and performs autonomous root cause analysis
type: application
version: 0.1.3
appVersion: "0.1.3"
keywords:
  - kubernetes
  - operator
  - sre
  - rca
  - root-cause-analysis
  - incident-management
  - ai
home: https://github.com/gaurangkudale/RCA-Operator
sources:
  - https://github.com/gaurangkudale/RCA-Operator
maintainers:
  - name: Gaurang Kudale
    url: https://github.com/gaurangkudale
icon: https://raw.githubusercontent.com/gaurangkudale/RCA-Operator/main-gk/docs/images/logo.png
kubeVersion: ">=1.26.0-0"
