apiVersion: v2
name: rca-operator
description: A Kubernetes-native incident detection operator with durable incident state and a built-in dashboard
type: application
version: 0.0.4
appVersion: "0.0.4"
keywords:
  - kubernetes
  - operator
  - sre
  - rca
  - root-cause-analysis
  - incident-management
home: https://github.com/gaurangkudale/RCA-Operator
sources:
  - https://github.com/gaurangkudale/RCA-Operator
maintainers:
  - name: Gaurang Kudale
    url: https://github.com/gaurangkudale
icon: https://raw.githubusercontent.com/gaurangkudale/RCA-Operator/main-gk/docs/images/logo.png
kubeVersion: ">=1.26.0-0"
